export const ROUTES = {
  home: (locale: string) => `/${locale}`,
  products: (locale: string) => `/${locale}/products`,
  productDetail: (locale: string, slug: string) => `/${locale}/products/${slug}`,
  blog: (locale: string) => `/${locale}/blog`,
  articleDetail: (locale: string, slug: string) => `/${locale}/article/${slug}`,
  events: (locale: string) => `/${locale}/events`,
  eventDetail: (locale: string, slug: string) => `/${locale}/events/${slug}`,
  community: (locale: string) => `/${locale}/community`,
  cart: (locale: string) => `/${locale}/cart`,
  checkout: (locale: string) => `/${locale}/checkout`,
  about: (locale: string) => `/${locale}/about`,
  contact: (locale: string) => `/${locale}/contact`,
  faq: (locale: string) => `/${locale}/faq`,
  signin: (locale: string, next?: string) => `/${locale}/auth/signin${next ? `?next=${encodeURIComponent(next)}` : ''}`,
  signup: (locale: string) => `/${locale}/auth/signup`,
  forgotPassword: (locale: string) => `/${locale}/auth/forgot-password`,
  account: (locale: string) => `/${locale}/account`,
  myOrders: (locale: string) => `/${locale}/account/my-orders`,
  myArticles: (locale: string) => `/${locale}/account/my-articles`,
  myComments: (locale: string) => `/${locale}/account/comments`,
  settings: (locale: string) => `/${locale}/account/settings`,
  admin: (locale: string) => `/${locale}/admin`,
} as const;
